// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFSVINttgKLtzuW7IZvlFzIBC_FcINFA',
    appId: '1:48129211872:web:de0b0a7071a99eeb50bf85',
    messagingSenderId: '48129211872',
    projectId: 'mobile-auth-test-30bb0',
    authDomain: 'mobile-auth-test-30bb0.firebaseapp.com',
    storageBucket: 'mobile-auth-test-30bb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJDATA-E2DioirXXvB3QdVAKW-T38onQ',
    appId: '1:48129211872:android:d656a545c82146a450bf85',
    messagingSenderId: '48129211872',
    projectId: 'mobile-auth-test-30bb0',
    storageBucket: 'mobile-auth-test-30bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORGfHr4bMowHgRw9H5uwE_oJqVvgaNl8',
    appId: '1:48129211872:ios:32effd6e1198adf750bf85',
    messagingSenderId: '48129211872',
    projectId: 'mobile-auth-test-30bb0',
    storageBucket: 'mobile-auth-test-30bb0.appspot.com',
    iosClientId:
        '48129211872-vg7gvjbtsro3oin28gmc3gpo30r8ur64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobAuthFireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORGfHr4bMowHgRw9H5uwE_oJqVvgaNl8',
    appId: '1:48129211872:ios:32effd6e1198adf750bf85',
    messagingSenderId: '48129211872',
    projectId: 'mobile-auth-test-30bb0',
    storageBucket: 'mobile-auth-test-30bb0.appspot.com',
    iosClientId:
        '48129211872-vg7gvjbtsro3oin28gmc3gpo30r8ur64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobAuthFireBase',
  );
}
